### ISSUE TITLE
Uncaught SyntaxError: Identifier 't' has already been declared

### ISSUE THREAD

**Issue by andjohansen** [jonkristian/entur-card#16]
Trying to get this card working. 
Copied the entur-card.js into my custom-lovelace folder and included with 
  - url: /local/custom-lovelace/entur-card.js
    type: js

When loading HA I get this error in my logs.
Uncaught SyntaxError: Identifier 't' has already been declared

Home Assistant 0.103.5
Frontend version: 20191204.1 - latest
Custom UIs:
CustomUI: 20190518

**Comment by andjohansen** [comment]
Configuration:

  - url: /local/custom-lovelace/entur-card.js
    type: js


  - title: Entur
    icon: mdi:bus
    path: "entur"
    panel: false
    cards:  
      - type: custom:entur-card
        name: Rutetider
        show_clock: true
        show_next: true
        show_human: true
        show_extra_departures: true
        entities:
          - entity: sensor.entur_bygdetunet
            name: Bygdetunet
          - entity: sensor.entur_eidsvoll_stasjon
            name: Eidsvoll Stasjon

**Comment by andjohansen** [comment]
`
  - title: Entur
    icon: mdi:bus
    path: "entur"
    panel: false
    cards:  
      - type: custom:entur-card
        name: Rutetider
        show_clock: true
        show_next: true
        show_human: true
        show_extra_departures: true
        entities:
          - entity: sensor.entur_bygdetunet
            name: Bygdetunet
          - entity: sensor.entur_eidsvoll_stasjon
            name: Eidsvoll Stasjon`

**Comment by andjohansen** [comment]
- title: Entur
    icon: mdi:bus
    path: "entur"    
    panel: false    
    cards:        
      - type: custom:entur-card      
        name: Rutetider
        show_clock: true
        show_next: true
        show_human: true
        show_extra_departures: true
        entities:
          - entity: sensor.entur_bygdetunet
            name: Bygdetunet
          - entity: sensor.entur_eidsvoll_stasjon
            name: Eidsvoll Stasjon

**Comment by andjohansen** [comment]
Formatting of the code is correct. Not sure how to copy/paste in here without it getting formatted

**Comment by jonkristian** [comment]
I can't reproduce this. Can you check your local `entur.js` just to make sure you have the full source? Try to restart and do a hard refresh on the webpage just to make sure everything is re-loaded? Also could you paste your entur configuration?

**Comment by andjohansen** [comment]
entur.js is copied raw from here. All lines are there. Done reboot and hard refresh on browser. 

entur sensor looks like this.
  - platform: entur_public_transport
    expand_platforms: true
    show_on_map: true
    stop_ids:
      - 'NSR:StopPlace:6865'
      - 'NSR:StopPlace:58844'

I can see the various entur sensors shows up in HA fine. 
sensor.entur_bygdetunet
sensor.entur_bygdetunet_platform_12712
sensor.entur_bygdetunet_platform_12713
sensor.entur_eidsvoll_stasjon
sensor.entur_eidsvoll_stasjon_platform_1
sensor.entur_eidsvoll_stasjon_platform_1_2
sensor.entur_eidsvoll_stasjon_platform_2
sensor.entur_eidsvoll_stasjon_platform_4
sensor.entur_eidsvoll_stasjon_platform_5

**Comment by andjohansen** [comment]
See some comments releated to moments.js. Should this be included somewhere?

**Comment by andjohansen** [comment]
I don't think the problem is related to the "Uncaught SyntaxError: Identifier 't' has already been declared" message. I see that this error is pretty random. It doesn't seem to appear any longer. But still I don't see anything from the card. Just completely blank page.

![image](https://user-images.githubusercontent.com/53919010/72241133-5602dd80-35e6-11ea-9e55-619b58ed8d64.png)

Code looks like this.
![image](https://user-images.githubusercontent.com/53919010/72241157-64e99000-35e6-11ea-8491-76f7ae65e22b.png)

![image](https://user-images.githubusercontent.com/53919010/72241302-bdb92880-35e6-11ea-9169-ade22b8231ef.png)

**Comment by andjohansen** [comment]
Got the card working now. I commented out the 2 lines 
            #show_next: true
            #show_human: true

if I enable these 2 lines the card doesn't work. 
Any idea?

**Comment by jonkristian** [comment]
Yes. I don't think you have the correct entity names, `entur_` was replaced with `transport_` a while back.
Try these:
```
sensor.transport_bygdetunet_platform_12712
sensor.transport_eidsvoll_stasjon
```

**Comment by andjohansen** [comment]
Ok. Went into the sensor and added name: Transport
Now the sensors shows up as you write above. 
But still the card is now showing up when setting show_next to true or show_human to true. 
If I set these to false, the card works.

**Comment by jonkristian** [comment]
Sorry I'm not entirely sure what you did. You can go to `.../developer-tools/state` to see all the sensors, just make sure that the ones you have corresponds with the ones listed. The error is due to non-existent entity. I've pushed some changes that will resolve in a warning if the entity was not found.

**Comment by jonkristian** [comment]
This works for me without any issues.
```
sensor:
  - platform: entur_public_transport
    name: Transport
    expand_platforms: true
    show_on_map: true
    stop_ids:
      - 'NSR:StopPlace:6865'
      - 'NSR:StopPlace:58844'
```
and
```
views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: custom:entur-card
        name: Rutetider
        show_clock: true
        show_next: true
        show_human: true
        show_extra_departures: true
        entities:
          - entity: sensor.transport_bygdetunet_platform_12712
            name: Bygdetunet
            destination: jessheim
          - entity: sensor.transport_eidsvoll_stasjon
            name: Eidsvoll Stasjon
            destination: oslo
```

If you're having trouble with the above, please make sure everything is up to date and clear browser cache too.
