### ISSUE TITLE
Not working with my Home Assistant

### ISSUE THREAD

**Issue by ronnyandre** [jonkristian/entur-card#18]
Using HACS to install the card, added the JS to the top of the lovelace file, and still the configuration gives me error:

```
- type: custom:entur-card
  name: Rutetider
  show_clock: true
  show_next: true
  show_human: true
  show_extra_departures: true
  entities:
    - entity: sensor.entur_bjornsletta_platform_1
      name: Bjørnsletta
      destination: Jernbanetorget
    - entity: sensor.entur_bjornsletta_platform_2
      name: Kolsås
      destination: Bjørnsletta
```

Gives me two errors:

1. ```No card type found```
2. ```Cannot read property 'setConfig' of undefined```
